name: "OdinPlusModUploader GitHub Action"
description: "Automate deploying mods with OdinPlusModUploader"
branding:
  icon: archive
  color: red
author: "Zt-freak"
inputs:
  nexusmod_mod_id:
    description: 'Nexusmods Mod id'
    required: true
  file:
    description: 'File to upload'
    required: true
  version:
    description: 'Mod version'
    required: true
  nexusmod_api_key:
    description: 'Nexusmods API key.'
    required: true
    default: ${{ secrets.NEXUSMOD_API_KEY }}
  nexusmod_cookie_nexusid:
    description: 'Nexusmods Cookie NexusId.'
    required: true
    default: ${{ secrets.NEXUSMOD_COOKIE_NEXUSID }}
  nexusmod_cookie_sid_develop:
    description: 'Nexusmods SID Develop.'
    required: true
    default: ${{ secrets.NEXUSMOD_COOKIE_SID_DEVELOP }}
runs:
  using: "composite"
  steps:
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore tools
      run: dotnet tool install -g Digitalroot.OdinPlusModUploader
      shell: bash

    - name: Upload
      env:
        NEXUSMOD_API_KEY: ${{ inputs.nexus-api-key }}
        NEXUSMOD_COOKIE_NEXUSID: ${{ inputs.nexusmod_cookie_nexusid }}
        NEXUSMOD_COOKIE_SID_DEVELOP: ${{ inputs.nexusmod_cookie_sid_develop }}
      run: |
        opmu nx check
        opmu nx upload ${{ inputs.nexus-mod-id }} ${{ inputs.file }}.zip -v ${{ inputs.version }} -d "OdinPlusModUploader (CI/CD)" -f ${{ inputs.file }} -dmv
