name: "OdinPlusModUploader GitHub Action"
description: "Automate deploying mods with OdinPlusModUploader"
branding:
  icon: archive
  color: red
author: "Zt-freak"
inputs:
  nexusmod_mod_id:
    description: 'Nexusmods Mod id'
    required: true
  file:
    description: 'File to upload'
    required: true
  nexusmod_api_key:
    description: 'Nexusmods API key.'
    required: true
    default: ${{ secrets.NEXUSMOD_API_KEY }}
  nexusmod_cookie_nexusid:
    description: 'Nexusmods Cookie NexusId.'
    required: true
    default: ${{ secrets.NEXUSMOD_COOKIE_NEXUSID }}
  nexusmod_cookie_sid_develop:
    description: 'Nexusmods SID Develop.'
    required: true
    default: ${{ secrets.NEXUSMOD_COOKIE_SID_DEVELOP }}
runs:
  using: "composite"
  steps:
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore tools
      run: dotnet tool install -g Digitalroot.OdinPlusModUploader
      shell: bash

    - name: Upload
      env:
        NEXUSMOD_API_KEY: ${{ secrets.nexus-api-key }}
        NEXUSMOD_COOKIE_NEXUSID: ${{ secrets.nexus-cookie-nxid-header }}
        NEXUSMOD_COOKIE_SID_DEVELOP: ${{ secrets.nexus-cookie-sid-header }}
      run: |
        opmu nx check
        opmu nx upload ${{ inputs.nexus-mod-id }} ${{ steps.download.outputs.download-path }}/${{ needs.prebuild.outputs.proj-file-name }}.v${{ needs.prebuild.outputs.next-tag }}.zip -v ${{ needs.prebuild.outputs.next-tag }} -d "OdinPlusModUploader (CI/CD)" -f ${{ needs.prebuild.outputs.proj-file-name }} -dmv
